// <auto-generated />
using System;
using FlightManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlightManagement.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210621043559_initdatabase")]
    partial class initdatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("FlightManagement.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlightID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlightNumberID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoOfPax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassengerCID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassengerName")
                        .HasColumnType("TEXT");

                    b.HasKey("BookingID");

                    b.HasIndex("FlightNumberID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("FlightManagement.Models.Flight", b =>
                {
                    b.Property<int>("FlightID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrivalCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeparterCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("FlightID");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightID = 1,
                            ArrivalCity = "Tp.Hochiminh",
                            DeparterCity = "Danang",
                            EndTime = "130559",
                            IsAvailable = true,
                            PassengerCapacity = 10,
                            StartTime = "113559"
                        },
                        new
                        {
                            FlightID = 2,
                            ArrivalCity = "Phuquoc",
                            DeparterCity = "Danang",
                            EndTime = "140559",
                            IsAvailable = true,
                            PassengerCapacity = 5,
                            StartTime = "113559"
                        });
                });

            modelBuilder.Entity("FlightManagement.Models.FlightNumber", b =>
                {
                    b.Property<int>("FlightNumberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlightID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoOfPax")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlightNumberID");

                    b.HasIndex("FlightID");

                    b.ToTable("FlightNumbers");
                });

            modelBuilder.Entity("FlightManagement.Models.Booking", b =>
                {
                    b.HasOne("FlightManagement.Models.FlightNumber", null)
                        .WithMany("Bookings")
                        .HasForeignKey("FlightNumberID");
                });

            modelBuilder.Entity("FlightManagement.Models.FlightNumber", b =>
                {
                    b.HasOne("FlightManagement.Models.Flight", null)
                        .WithMany("FlightNumbers")
                        .HasForeignKey("FlightID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlightManagement.Models.Flight", b =>
                {
                    b.Navigation("FlightNumbers");
                });

            modelBuilder.Entity("FlightManagement.Models.FlightNumber", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
